ustacks -t gzfastq -f ./sampleI/include/Ebritti822.fq.gz -o ./stacks/ -i 1 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Lferxi9829.fq.gz -o ./stacks/ -i 2 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Pulochir76.fq.gz -o ./stacks/ -i 3 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ajordani86.fq.gz -o ./stacks/ -i 4 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Lrutteri56.fq.gz -o ./stacks/ -i 5 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ecaudatus2.fq.gz -o ./stacks/ -i 6 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Pdactyl08.fq.gz -o ./stacks/ -i 7 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ccandidus.fq.gz -o ./stacks/ -i 8 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ecaudatus3.fq.gz -o ./stacks/ -i 9 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ccfcypselur.fq.gz -o ./stacks/ -i 10 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Pdactyl51.fq.gz -o ./stacks/ -i 11 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ccfmelanu2.fq.gz -o ./stacks/ -i 12 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Lnanus2476.fq.gz -o ./stacks/ -i 13 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Crystall87.fq.gz -o ./stacks/ -i 14 -m 3 -p 15
#ustacks -t gzfastq -f ./sampleI/include/Cbowersian.fq.gz -o ./stacks/ -i 15 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Cscottae04.fq.gz -o ./stacks/ -i 16 -m 3 -p 15
#ustacks -t gzfastq -f ./sampleI/include/Cstauffe11.fq.gz -o ./stacks/ -i 17 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ajordani89.fq.gz -o ./stacks/ -i 18 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ajordan521.fq.gz -o ./stacks/ -i 19 -m 3 -p 15
#ustacks -t gzfastq -f ./sampleI/include/Cmelanu89.fq.gz -o ./stacks/ -i 20 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ccomus970.fq.gz -o ./stacks/ -i 21 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Eorbis821.fq.gz -o ./stacks/ -i 22 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ecaudatus4.fq.gz -o ./stacks/ -i 23 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Cmelanu88.fq.gz -o ./stacks/ -i 24 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Lflorae666.fq.gz -o ./stacks/ -i 25 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ajordan522.fq.gz -o ./stacks/ -i 26 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Pptychoman.fq.gz -o ./stacks/ -i 27 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ecaudatus1.fq.gz -o ./stacks/ -i 28 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Cgilberti81.fq.gz -o ./stacks/ -i 29 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Npelagicus.fq.gz -o ./stacks/ -i 30 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ccandidu2.fq.gz -o ./stacks/ -i 31 -m 3 -p 15
#ustacks -t gzfastq -f ./sampleI/include/Eorbis223.fq.gz -o ./stacks/ -i 32 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ccomus971.fq.gz -o ./stacks/ -i 33 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Lgibbus176.fq.gz -o ./stacks/ -i 34 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Cfaunus841.fq.gz -o ./stacks/ -i 35 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Aungak696.fq.gz -o ./stacks/ -i 36 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ccfmelanu1.fq.gz -o ./stacks/ -i 37 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Cstauffe96.fq.gz -o ./stacks/ -i 38 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Eorbis461.fq.gz -o ./stacks/ -i 39 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Cfurcellu98.fq.gz -o ./stacks/ -i 40 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Cscottae02.fq.gz -o ./stacks/ -i 41 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Cphasma07.fq.gz -o ./stacks/ -i 42 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Crystalli2.fq.gz -o ./stacks/ -i 43 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Crystalli1.fq.gz -o ./stacks/ -i 44 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Cphasma61.fq.gz -o ./stacks/ -i 45 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Lgibbus043.fq.gz -o ./stacks/ -i 46 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Ppenicillu.fq.gz -o ./stacks/ -i 47 -m 3 -p 15
ustacks -t gzfastq -f ./sampleI/include/Rattenuatu.fq.gz -o ./stacks/ -i 48 -m 3 -p 15