ustacks -t gzfastq -f ./samples/Ebritti822.fq.gz -o ./stacks/ -i 1 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Lferxi9829.fq.gz -o ./stacks/ -i 2 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Pulochir76.fq.gz -o ./stacks/ -i 3 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ajordani86.fq.gz -o ./stacks/ -i 4 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Lrutteri56.fq.gz -o ./stacks/ -i 5 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ecaudatus2.fq.gz -o ./stacks/ -i 6 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Pdactyl08.fq.gz -o ./stacks/ -i 7 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ccandidus.fq.gz -o ./stacks/ -i 8 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ecaudatus3.fq.gz -o ./stacks/ -i 9 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ccfcypselur.fq.gz -o ./stacks/ -i 10 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Pdactyl51.fq.gz -o ./stacks/ -i 11 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ccfmelanu2.fq.gz -o ./stacks/ -i 12 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Lnanus2476.fq.gz -o ./stacks/ -i 13 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Crystall87.fq.gz -o ./stacks/ -i 14 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cbowersian.fq.gz -o ./stacks/ -i 15 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cscottae04.fq.gz -o ./stacks/ -i 16 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cstauffe11.fq.gz -o ./stacks/ -i 17 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ajordani89.fq.gz -o ./stacks/ -i 18 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ajordan521.fq.gz -o ./stacks/ -i 19 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cmelanu89.fq.gz -o ./stacks/ -i 20 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ccomus970.fq.gz -o ./stacks/ -i 21 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Eorbis821.fq.gz -o ./stacks/ -i 22 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ecaudatus4.fq.gz -o ./stacks/ -i 23 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cmelanu88.fq.gz -o ./stacks/ -i 24 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Lflorae666.fq.gz -o ./stacks/ -i 25 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ajordan522.fq.gz -o ./stacks/ -i 26 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Pptychoman.fq.gz -o ./stacks/ -i 27 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ecaudatus1.fq.gz -o ./stacks/ -i 28 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cgilberti81.fq.gz -o ./stacks/ -i 29 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Npelagicus.fq.gz -o ./stacks/ -i 30 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ccandidu2.fq.gz -o ./stacks/ -i 31 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Eorbis223.fq.gz -o ./stacks/ -i 32 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ccomus971.fq.gz -o ./stacks/ -i 33 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Lgibbus176.fq.gz -o ./stacks/ -i 34 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cfaunus841.fq.gz -o ./stacks/ -i 35 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Aungak696.fq.gz -o ./stacks/ -i 36 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ccfmelanu1.fq.gz -o ./stacks/ -i 37 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cstauffe96.fq.gz -o ./stacks/ -i 38 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Eorbis461.fq.gz -o ./stacks/ -i 39 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cfurcellu98.fq.gz -o ./stacks/ -i 40 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cscottae02.fq.gz -o ./stacks/ -i 41 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cphasma07.fq.gz -o ./stacks/ -i 42 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Crystalli2.fq.gz -o ./stacks/ -i 43 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Crystalli1.fq.gz -o ./stacks/ -i 44 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Cphasma61.fq.gz -o ./stacks/ -i 45 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Lgibbus043.fq.gz -o ./stacks/ -i 46 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Ppenicillu.fq.gz -o ./stacks/ -i 47 -m 3 -p 15
ustacks -t gzfastq -f ./samples/Rattenuatu.fq.gz -o ./stacks/ -i 48 -m 3 -p 15